version: '2'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["./run.sh"]
    image: templastic/bash
    restart: unless-stopped
    volumes:
      - ./src:/app
